theme: jekyll-theme-cayman
ico: favicon.ico
icon: favicon.ico
favicon: favicon.ico
lang: "en", lang="en-US", lang="ar", lang="eg", lang="cn", lang="zh"
lang="en", lang="en-US", lang="ar", lang="eg", lang="cn", lang="zh"
