theme: jekyll-theme-cayman
title: "Windows OS Desktop PC Kugou Music Player Download Tool & Go"
description: Kugou Downloader Windows OS Desktop PC Kugou Music Player Download 
#show_nav: false
show_sidebar: true
show_downloads: true
download_url: https://github.com/CreateDownloader/KugouDownloaderNew/releases/download/Debug/Debug.KugouMusicDownloader.GO.EXE.zip

#favicon: favicon.ico
#icon: favicon.ico
#ico: favicon.ico
#logo: /assets/img/logo.png
#google_analytics:
#encoding: UTF-8
#plugins:
#  - jekyll-octicons  
#github:
#  is_project_page: true
#  owner_name: KugouDownloaderNew
#  owner_url: https://github.com/CreateDownloader/KugouDownloaderNew


#exclude:
#  - package.json
#  - node_modules
#  - gulpfile.js
#  - package-lock.json
#  - Gemfile
#  - Gemfile.lock
#  - src 


#favicon: favicon.ico
#icon: favicon.ico
#ico: favicon.ico

#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
